### ISSUE TITLE
Reporte en .pdf de la Familia

### ISSUE THREAD

**Issue by juventudproductivabicentenaria** [juventudproductivabicentenaria/tuconsejocomunal#45]
En el botón Acción del registro de familia, se le debe colocar una opción de generar reporte  de la familia.
En este link esta la [planilla 1 ejemplo](https://github.com/juventudproductivabicentenaria/tuconsejocomunal/blob/master/docs/estudio_demogr%C3%A1fico.png) y [planilla 2 ejemplo](https://github.com/juventudproductivabicentenaria/tuconsejocomunal/blob/master/docs/planilla%20situaci%C3%B3n%20econ%C3%B3nica.png)

Notas: Algunas pregunta de la planilla 2 se le cambio la redacción el la encuesta, la encuesta a tomar de referencia es la del jefe de familia (Ya que la encuesta se le puede hacer a cada miembro de la familia)

**Comment by juventudproductivabicentenaria** [comment]
grupo 4: Laplante y Villamizar

**Comment by isajhon** [comment]
buenas noches 

Se adjunta presentación de la planilla de registro del estudio socioeconomico familiar y el PDF que generará el sistema.


[Uploading presentacion de reporte21.docx…]()

**Comment by isajhon** [comment]
[presentacion de reporte21.docx](https://github.com/juventudproductivabicentenaria/tuconsejocomunal/files/1199030/presentacion.de.reporte21.docx)

**Comment by isajhon** [comment]
buenas noches

Se adjunta diseño de la planilla de registro del estudio socioeconomico familiar y el PDF que generará el sistema.
[presentacion de reporte.docx](https://github.com/juventudproductivabicentenaria/tuconsejocomunal/files/1199036/presentacion.de.reporte.docx)
